### ISSUE TITLE
Typecript Error:  Type 'undefined' is not assignable to type 'IDictionary<IControlType<IViewBased<IViewOptions> | IJodit | IFileBrowser, IToolbarButton>>'

### ISSUE THREAD

**Issue by kanke** [jodit/jodit-react#115]
Using the latest version of ` "jodit-react": "^1.0.68"` , ` "react": "^16.9.0"` and `"typescript": "^3.9.6" `but getting the below errors. Kindly assist

` ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts
[tsl] ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts(28,13)
      TS1109: Expression expected.

ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts
[tsl] ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts(33,7)
      TS2532: Object is possibly 'undefined'.

ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts
[tsl] ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts(35,8)
      TS2532: Object is possibly 'undefined'.

ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts
[tsl] ERROR in /node_modules/jodit/src/core/ui/helpers/get-control-type.ts(40,43)
      TS2345: Argument of type 'Controls | undefined' is not assignable to parameter of type 'Controls'.
  Type 'undefined' is not assignable to type 'IDictionary<IControlType<IViewBased<IViewOptions> | IJodit | IFileBrowser, IToolbarButton>>'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] Command execution failed`

Anyone seeing this?

**Comment by andrem0** [comment]
@kanke did you find a solution to this?

As far as I can tell it's the logical assignment "||=" in get-control-type.ts that gives the error:

`export function getControlType(
	button: IControlType | string,
	controls: CanUndef<Controls>
): IControlTypeStrong {
	let buttonControl: IControlTypeStrong;

	controls ||= Config.defaultOptions.controls;

	if (!isString(button)) {
		buttonControl = { name: 'empty', ...button };

		if (controls[buttonControl.name] !== undefined) {
			buttonControl = {
				...controls[buttonControl.name],
				...buttonControl
			} as IControlTypeStrong;
		}
	} else {
		buttonControl = findControlType(button, controls) || {
			name: button,
			command: button,
			tooltip: button
		};
	}

	return buttonControl;
}`

**Comment by kanke** [comment]
No I haven't unfortunately.

**Comment by kanke** [comment]
No I haven't unfortunately.

**Comment by kanke** [comment]
Try upgrading to typescript@4.1.3

**Comment by kanke** [comment]
https://github.com/jodit/jodit-react/issues/116#issuecomment-761240479
