### ISSUE TITLE
why i type multiple characters but only appear 1 character.

### ISSUE THREAD

**Issue by feiraelectronica** [jodit/jodit-react#119]
hi, i'm having an issue. for example. i type 'test'. but only appear 't'. i need to type t then left click mouse, then type the next character. Please, it's urgent.

**Comment by feiraelectronica** [comment]
i realize the issue is because of the onChange. it re-load the content which avoid me from entering the second character. need to click in the text editor first so i can type the next character

**Comment by feiraelectronica** [comment]
this is my code

![image](https://user-images.githubusercontent.com/72189108/103341884-06514680-4ac3-11eb-8c52-93331954e627.png)

i'm using class component. can you show me how its done for class component. i think maybe because of that

![image](https://user-images.githubusercontent.com/72189108/103341952-31d43100-4ac3-11eb-9886-a6c62bf7a9e3.png)

**Comment by feiraelectronica** [comment]
i think it is the same issue as #43

**Comment by Fedeorlandau** [comment]
@feiraelectronica  this is because you're defining the config inside the scope of the react component.
```
const config = { readonly: false }

const Example ({}) => <JoditEditor config={config} />

```

Cheers,

**Comment by feiraelectronica** [comment]
> @feiraelectronica this is because you're defining the config inside the scope of the react component. Every time you type, the setContent function runs and re-renders the component and since you're "Creating" a new config on every render, you lose focus of the RTE and you need to click it again.
> 
> ```
> const config = { readonly: false }
> 
> const Example ({}) => <JoditEditor config={config} />
> ```
> 
> Cheers,

wow it works. thank you so much. will close this now.
