### ISSUE TITLE
using onBlur makes me click twice each button.

### ISSUE THREAD

**Issue by Octopusboom** [jodit/jodit-react#123]
I am using the editor like this: 

`  const onBlur = (event) => {
    const editorValue = event.target.innerHTML;
    setEditorContent(editorValue);
  };`

`        <JoditEditor
          ref={editor}
          value={editorContent}
          config={config}
          tabIndex={1} // tabIndex of textarea
          onBlur={onBlur}
          onChange=''
        />`

Evetime I click any button from the editor, I have to click twice in order to work.

Can you please help me in this matter?

Thank you!

**Comment by Xopsy** [comment]
I had the same issue, I could only fix this issue in this way.

  ```
// Editor Jodit
  const editorJodit = React.useRef(null);
  const [value, setValue] = useState("");
  const onBlurEditor = () => {
    console.log("onBlurEditor", editorJodit.current.value);
    setValue(editorJodit.current.value);
  };
  const onEditorChange = (editorNewValue: string) => {
    console.log("onEditorChange", editorNewValue);
  };
  return (
    <JoditEditor
      ref={editorJodit}
      config={{
        disablePlugins: "video,file,print",
      }}
      name="content"
      onChange={onEditorChange}
      onBlur={onBlurEditor}
      tabIndex={1}
      value={value}
    />
  );
```

And also you will solve the issue with onChange loosing focus. I hope it will work for you

**Comment by Octopusboom** [comment]
Thank you for your answer, it partially fixed my problem in terms that I can see live in the console log the content. But still, when I try to upload an image or see the code, I have to click twice. It drives me nuts! :P

**Comment by Xopsy** [comment]
It could be because of active plugins ??? It is a suppose, in my side it is not happening this problem with my code above I have got this plugins disable "video,file,print,symbols".

**Comment by Octopusboom** [comment]
> It could be because of active plugins ??? It is a suppose, in my side it is not happening this problem with my code above I have got this plugins disable "video,file,print,symbols".

I have manage to fix it. The code now is like this:

`  const onBlurEditor = (event) => {
    event.preventDefault();
    event.stopPropagation();
    editor.current.value;
  };

  const onEditorChange = (editorNewValue) => {
    console.log('onEditorChange', editorNewValue);
    editor.current.value = editorNewValue;
  };

<JoditEditor
          ref={editor}
          name='content'
          value={editorContent}
          config={config}
          tabIndex={1} // tabIndex of textarea
          onBlur={onBlurEditor}
          onChange={onEditorChange}
        />
`
