### ISSUE TITLE
Remove <p> from content added from external buttons

### ISSUE THREAD

**Issue by Octopusboom** [jodit/jodit-react#124]
Hello!

I have some external buttons that are adding some string into the editor when pressed. The problem is that it always ads <p></p> tags aroud the text. 

my button function is:   ```
const addStuff = () => {
    setEditorContent(editor.current.value + '{stuff2add}');
  };
```
and the result is `<p>{stuff2add}</p>`

Does anyone has any ideea in how to drop the p tags?

Thank you!

**Comment by Octopusboom** [comment]
The issues is fixed. If anyone needs this, please find the code below:

` let editorRef;
  const editor = useRef(null);
  const [editorContent, setEditorContent] = useState('');`

`  const addSomeTextToEditor= () => {
    let textContainer = document.createElement('span');
    textContainer.innerHTML = 'add custom text to the editor on click';
    editorRef.selection.insertNode(textContainer);
  };`

`        <JoditEditor
          editorRef={(ref) => {
            editorRef = ref;
          }}
          ref={editor}
          name='content'
          value={editorContent}
          config={config}
          tabIndex={1} // tabIndex of textarea
          onBlur={onBlurEditor}
          onChange={onEditorChange}
        />
<button on click={addSomeTextToEditor}>Add text </button>
`

**Comment by Shahilgope1520** [comment]
> The issues is fixed. If anyone needs this, please find the code below:
> 
> ` let editorRef; const editor = useRef(null); const [editorContent, setEditorContent] = useState('');`
> 
> ` const addSomeTextToEditor= () => { let textContainer = document.createElement('span'); textContainer.innerHTML = 'add custom text to the editor on click'; editorRef.selection.insertNode(textContainer); };`
> 
> ` <JoditEditor editorRef={(ref) => { editorRef = ref; }} ref={editor} name='content' value={editorContent} config={config} tabIndex={1} // tabIndex of textarea onBlur={onBlurEditor} onChange={onEditorChange} /> <button on click={addSomeTextToEditor}>Add text </button>`

can you give full code and there is one more problem
on button click if we add text cursor don;t move

**Comment by Maddumage** [comment]
@Octopusboom, There is no property called editorRef in JoditEditor. I am using Typescript.
