### ISSUE TITLE
Features fail after build

### ISSUE THREAD

**Issue by amrita-syn** [jodit/jodit-react#13]
Using Jodit-react as part of a react application with Jodit in its own component. However, when I build the app and serve from the build directory on Apache server, the editor has numerous issues. E.g. the right tool is not highlighted for bold/italic/underline content, changing text size fails, etc.

Expected behavior:
Should perform as expected when app is built as a static site.
Actual behavior:
After build process, features fail to work as expected.

Check deployed editor - https://amrita-syn.github.io/react-jodit/

P.S. Also opened an issue in [Jodit](https://github.com/xdan/jodit/issues/225) itself; Can't say if the issue is with react build or jodit, hence duplicating.

**Comment by amrita-syn** [comment]
Since last, I have also tried the react application with the main jodit package and the issue remains.

**Comment by tandrys** [comment]
run  `npm run build --target es6`, I can use all features.
source: https://stackoverflow.com/questions/30439869/can-typescript-compile-to-es6-code

**Comment by amrita-syn** [comment]
My workaround was to add it as a script tag in `public/index.html`. 
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jodit/3.2.55/jodit.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/jodit/3.2.55/jodit.min.js"></script>
```
And then use in components like so -
```
const Jodit = window.Jodit;
const editor = new Jodit('#editor');
```

**Comment by vladimyr** [comment]
This is not `jodit-react` specific, it comes bundled with all Jodit _flavors_ due to: https://github.com/xdan/jodit/issues/225#issuecomment-546524371
