### ISSUE TITLE
hovering over the text editor triggers hover over source button instantly

### ISSUE THREAD

**Issue by selimmattar** [jodit/jodit-react#138]
Whenever I hover with the mouse over the text editor it seems that the source button is hovered by default and every click anywhere results in a click on the source button

Version ^1.0.86

Demo : 

https://user-images.githubusercontent.com/20337258/118490213-fe1a4080-b71d-11eb-93eb-c359251615d1.mov

**Comment by xdan** [comment]
Can you show your styles for this button? Or open example page

**Comment by xdan** [comment]
https://user-images.githubusercontent.com/794318/121383046-d2baf800-c94f-11eb-8edb-965da7b30614.mov

**Comment by selimmattar** [comment]
Thanks a lot! It's working well. Much appreciated
