### ISSUE TITLE
Link disabled

### ISSUE THREAD

**Issue by KellyLMartin** [jodit/jodit-react#167]
Using jodit-react version 1.1.17

<img width="1440" alt="Screen Shot 2022-01-11 at 12 56 09 PM" src="https://user-images.githubusercontent.com/47371979/148996561-69bd515a-64e0-452b-bec9-8aa94398b178.png">

While trying to add a link, all of the textboxes are disabled (URL, text, class name). Can't find a way to make this enabled. Is there a config I need to enable?

My config is - 

```
  const [config, setConfig] = useState({
    readonly: false,
    toolbar: true,
    uploader: {
      insertImageAsBase64URI: true,
      imagesExtensions: ['jpg', 'png', 'jpeg', 'gif'],
    },
  })
```

Jodit component code - 

```
      <JoditEditor
        ref={editor}
        width={'auto'}
        height={1000}
        config={config}
        onChange={handleTextAreaChange}
        value={textAreaValue}
        tabIndex={1} // tabIndex of textarea
        onBlur={newContent => setContent(newContent)}
      />
```

**Comment by lbrcs** [comment]
hi kelly, i am currently struggling with the same issue. how did you manage to fix it?
