### ISSUE TITLE
<ForwardRef> component: Uncaught Error: Permission denied to access property "ownerDocument"

### ISSUE THREAD

**Issue by DeveloperOl** [jodit/jodit-react#173]
Hi @all,
I recently started using jodit and like the features and simplicity. Nonetheless, when I have many, fast occuring state changes in my react app the whole application crashes with the following message. Is there a way I can catch or prevent this error in my app or in the jodit source?

![image](https://user-images.githubusercontent.com/46971268/154034568-e8286792-3053-4e78-b180-86040ec185c6.png)

![image](https://user-images.githubusercontent.com/46971268/154034700-88b41f18-ae9c-46cb-aefb-b85a10afac19.png)

**Comment by xdan** [comment]
Are you using an iframe?

**Comment by DeveloperOl** [comment]
no iFrame, just a plain react app using redux

**Comment by DeveloperOl** [comment]
@xdan I did some further investigation and so far commenting out 
```
if (textArea?.current) {
    textArea.current.destruct()
}
```
in the `JoditEditor.js` class (Line 35) seems to fix the issue for me. Any idea why and how this can be solved permanently? I'll leave the change for a while and will test, if this remains fixed.

**Comment by xdan** [comment]
I realised what you are doing. You take a reference to Jodit via ref.current and then use it even after the editor has been destroyed. You can't do that.
Look at the code that set Jodit.value directly. Probably there is a bug that instance is used even after the component is removed.

**Comment by DeveloperOl** [comment]
Maybe I don't understand it correctly, but I don't think the editor is being destroyed during usage of the app...
Here is my code:
In the rendered class I use:

```
<Box width={1}>
    <Editor
        value={activeFinding.evidence ? activeFinding.evidence : ""}
        onBlur={(e) => { setActiveFindingKey("evidence", e) }}
    />
</Box>
```

Where activeFinding is a redux state variable, which is updated very frequently (sometimes multiple times per second) and defined as `const activeFinding = useSelector((state) => state.activeFinding);`
and <Editor> is a custom, reusable class defined as:

```
import JoditEditor from "jodit-react";
import React from "react";

export default function Editor(props) {
    const { onBlur, ...other } = props;
    const ref = React.createRef(null)

    const config = {
        readonly: false,
        theme: "dark",
        showPlaceholder: false,
        hidePoweredByJodit: true,
        askBeforePasteFromWord: false,
        askBeforePasteHTML: false,
        addNewLineOnDBLClick: false,
        enableDragAndDropFileToEditor: false,
        spellcheck: false,
        cleanHTML: {
            cleanOnPaste: false,
            removeOnError: true,
            safeJavaScriptLink: true,
            denyTags: { script: true }
        },
        autofocus: false,
        controls: {
            font: {
                list: {
                    'Raleway Light': 'Rale'
                }
            }
        },
        buttons: "bold italic underline strikethrough eraser ul ol indent outdent align paragraph brush image table link source"
    };

    /**  Input formatting */
    /**/ const style = "font-family: &quot;Raleway Light&quot;; font-size: 11pt";
    /**/ const prefix = `<body style="${style}">`;
    /**/ const suffix = "</body>"
    return (
        <div>
            <JoditEditor
                config={config}
                tabIndex={0}
                onBlur={(e) => onBlur(`${prefix}${e}${suffix}`)}
                ref={ref}
                {...other}
            />
        </div>
    );
}
```

The rendered Class does not unmount during the whole time.

**Comment by xdan** [comment]
Move `const config = {` outside of "function editor("
The editor is reinitialized on every render.
Or use useMemo

**Comment by DeveloperOl** [comment]
This seems to have fixed the issue! I can not reproduce it anymore after moving the constants out of the Editor function. I will do some further testing, but closing this for now.
Can you explain, why there is a difference when defining the constants outside of the Editor function?

**Comment by xdan** [comment]
<JoditEditor will reinitialize the editor when new settings come in, when you set a constant inside a function, it is created on every render, a new one.
