### ISSUE TITLE
Jodit not cleaning up after unmount

### ISSUE THREAD

**Issue by KevinDenys** [jodit/jodit-react#196]
Everytime a React Jodit instance is rendered a div is added to the dom
![image](https://user-images.githubusercontent.com/17174443/172570564-8d198039-6b33-4d94-bb5b-823c2d162368.png)
When changing the page (unmounting) the component the div is still visible in the dom. After using the application you can have 100+ div elements cluttering the dom. 

![image](https://user-images.githubusercontent.com/17174443/172570888-85b84a94-2345-40f4-85b8-7bb2be4f18b6.png)

**Comment by xdan** [comment]
Fixed in 1.3.18
