### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by semiromid** [jodit/jodit-react#2]
Hello. I get error. I use React Js + Redux

jodit.min.js:10 Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined
    at Object.t.$$ (jodit.min.js:10)
    at e.<anonymous> (jodit.min.js:10)
    at jodit.min.js:10
t.$$ @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
setTimeout (async)
(anonymous) @ jodit.min.js:10
p @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
e.eachEvent @ jodit.min.js:10
e.fire @ jodit.min.js:10
t.setEditorValue @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
p @ jodit.min.js:10
07:29:58.865 jodit.min.js:10 Uncaught TypeError: Cannot read property 'fire' of undefined
    at e.<anonymous> (jodit.min.js:10)
    at jodit.min.js:10
(anonymous) @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
setTimeout (async)
(anonymous) @ jodit.min.js:10
p @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
e.eachEvent @ jodit.min.js:10
e.fire @ jodit.min.js:10
t.setEditorValue @ jodit.min.js:10
(anonymous) @ jodit.min.js:10
p @ jodit.min.js:10
07:29:58.973 jodit.min.js:10 Uncaught TypeError: Cannot read property 'current' of undefined
    at t.calcPathImd (jodit.min.js:10)
    at jodit.min.js:10

**Comment by xdan** [comment]
How repeat?

**Comment by petermk** [comment]
There are multiple bugs in the current code.
1). 
`import Jodit from 'jodit';`
 should be 
`import Jodit from 'Jodit';`
2). The errors above are caused by `config={{ }}`
Instead, you should add something like:
`this.config = {
      minHeight: 300
 };`

and then use it like this:
`<JoditEditor value={this.state.content} config={this.config} onChange={this.updateContent.bind(this)} />`

**Comment by sandroweb** [comment]
![image](https://user-images.githubusercontent.com/260201/66127405-f6963a00-e5c1-11e9-8265-ade7170a7221.png)

My imports:
```
import 'jodit';
import 'jodit/build/jodit.min.css';
import JoditEditor from "jodit-react";
```

My `this.state.config` are not empty.

`<JoditEditor editorRef={ this.state.editorRed } value={ this.state.value } config={ this.state.config } onChange={ value => this.onChange(value) />`

You know about this errors?

**Comment by es27** [comment]
> There are multiple bugs in the current code.
> 1).
> `import Jodit from 'jodit';`
> should be
> `import Jodit from 'Jodit';`
> 2). The errors above are caused by `config={{ }}`
> Instead, you should add something like:
> `this.config = { minHeight: 300 };`
> 
> and then use it like this:
> `<JoditEditor value={this.state.content} config={this.config} onChange={this.updateContent.bind(this)} />`


config does not accept props

in the src/index:
textArea.current = new Jodit (textArea.current, customConfig)
should be textArea.current = new Jodit (textArea.current, config) 

but then you will get other issues
