### ISSUE TITLE
performance issue/slow 

### ISSUE THREAD

**Issue by corelus** [jodit/jodit-react#209]
After adding the Jodit element, typing in all other fields in the page are slow and sometime even the typed text is displayed with delay of 10 seconds. Strangly, this happens when I add some config parameters.

**Comment by xdan** [comment]
Show me your code please

**Comment by corelus** [comment]
(https://user-images.githubusercontent.com/6502834/189671860-69b7ba85-4318-4f5f-ac41-3e2ffd75380c.png)

**Comment by corelus** [comment]
![Bildschirmfoto 2022-09-12 um 3 54 13 PM](https://user-images.githubusercontent.com/6502834/189672187-8fe80f0d-b7d0-4b98-9560-df2311e1dc6e.png)
