### ISSUE TITLE
Even though I disable some editor plugins, they are displayed on mobile

### ISSUE THREAD

**Issue by Tahmasb** [jodit/jodit-react#243]
**Jodit Version:**  1.3.39

**Browser:**  Chrome
**OS:**  phone android
**Is React App:** true (in next.js app)

**Code**
"use client"
import styles from "./editor.module.css"

import JoditEditor from "jodit-react"
import { Grid } from "@mui/material"

const Editor = ({ mainRef }) => {
  const config = {
    height: "400px",
    direction: "rtl",
    disablePlugins: [
      "table",
      "video",
      "file",
      "symbols",
      "print",
      "bold",
      "about",
      "indent",
      "redo-undo",
      "search",
      "font",
      "ordered-list",
      "image",
      "preview",
      "fullsize",
      "hr",
      // "link",
      "line-height",
      "justify",
      // "format-block",
      "class-span",
      "clean-html",
      "clipboard",
      "color",
      "spellcheck",
    ],
  }
  return (
    <Grid className={styles.container}>
      <JoditEditor ref={mainRef} config={config} />
    </Grid>
  )
}
export default Editor

I disabled some plugins, but these plugins are disabled only on the desktop (Windows). But I want these plugins to be disabled in the mobile version, but this is not happening.
What should I do to do this?

**Expected behavior:**
I expect that the plugins I disabled will also be disabled in the mobile version, but they will be disabled only in the computer(descotp)

**Actual behavior:**
But what happens is that my settings are only applied to desktop and not to mobile

**Comment by Tahmasb** [comment]
What I realized now is that it doesn't matter if it's a mobile phone or a desktop. Whenever the screen size is reduced, those plugins that I disabled will be displayed

**Comment by rastermechanism** [comment]
Hello, have any one found any solution for this?  On mobile all icons are coming which make it clumsy.
