### ISSUE TITLE
when print, image not printed

### ISSUE THREAD

**Issue by denny-zefanya** [jodit/jodit-react#247]
**Jodit Version:**  3.4.xxxxx

**Browser:*Chrome*  
**OS:*Windows*  
**Is React App:*True*  

**Code**

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**When in editor image is displayed, when I try to print using print button on jodit toolbar image suppose to printed

**Actual behavior:** Image not printed when I try to print using print button on jodit toolbar

**Comment by denny-zefanya** [comment]
i solved it by set timeout when print

**Comment by FabDonRixos** [comment]
> i solved it by set timeout when print

How did you set a timeout on Print, could you give me a Code example.

**Comment by FabDonRixos** [comment]
> i solved it by set timeout when print

@denny-zefanya
How did you set a timeout on Print, could you give me a Code example.

**Comment by ZhaoMuqiang** [comment]
how to set timout when print?
