### ISSUE TITLE
Cannot read property 'fire' of undefined / Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by sandroweb** [jodit/jodit-react#25]
![image](https://user-images.githubusercontent.com/260201/66224237-c7f48e00-e6ab-11e9-9ee1-575eb133f893.png)

Package.json
```
"jodit": "^3.2.55",
"jodit-react": "^1.0.26",
```

My imports:
```
import 'jodit';
import 'jodit/build/jodit.min.css';
import JoditEditor from "jodit-react";
```

My `this.state.config` are not empty.

`<JoditEditor editorRef={ this.state.editorRed } value={ this.state.value } config={ this.state.config } onChange={ value => this.onChange(value) />`

You know about this errors?

**Comment by GeorgeStratulat** [comment]
https://github.com/jodit/jodit-react/issues/4#issuecomment-411830674 
This one worked for me.

**Comment by netcoding87** [comment]
Hey, had the same error when setting up Jodit-react in my project. Finally I solved it this way:

```javascript
const config = {
  readonly: false,
  // and more...
}

const Editor: React.FC = () => {
  const editor = useRef(null)
  const [content, setContent] = useState('')

  return (
    <JoditEditor
      ref={editor}
      value={content}
      config={config}
      onChange={newContent => setContent(newContent)}
    />
  )
}
```

It seems that the config object is not allowed to be inside of the react function component (as it is in the readme.md)

**Comment by Arbigaus** [comment]
> Hey, had the same error when setting up Jodit-react in my project. Finally I solved it this way:
> 
> ```js
> const config = {
>   readonly: false,
>   // and more...
> }
> 
> const Editor: React.FC = () => {
>   const editor = useRef(null)
> 
>   return (
>     <JoditEditor
>       ref={editor}
>       value={''}
>       config={config}
>       onChange={newContent => console.log(newContent)}
>     />
>   )
> }
> ```
> 
> It seems that the config object is not allowed to be inside of the react function component (as it is in the readme.md)

Didn't work for me...

**Comment by masbaehr** [comment]
It seems this error is still happening as of today. This should be addressed at it is very annoying and there seems to be no logical reason for it. I spent almost an hour finding a solution for this.

Not working (causing exception)
```javascript
 <JoditEditor
             
                value={myObject.content}
                config={{
  readonly: false
}}
                tabIndex={1}
                onBlur={newContent => {}} 
                onChange={newContent => {}}
            />
```


Working:
```javascript
 <JoditEditor
             
                value={myObject.content}
                config={joditConfig}
                tabIndex={1} 
                onBlur={newContent => {}} 
                onChange={newContent => {}}
            />
```
while joditConfig being OUTSIDE of the functional component scope

**Comment by HarishSha** [comment]
You can use this https://github.com/jodit/jodit-react/issues/4#issuecomment-582411368

**Comment by sandroweb** [comment]
> Hey, had the same error when setting up Jodit-react in my project. Finally I solved it this way:
> 
> ```js
> const config = {
>   readonly: false,
>   // and more...
> }
> 
> const Editor: React.FC = () => {
>   const editor = useRef(null)
> 
>   return (
>     <JoditEditor
>       ref={editor}
>       value={''}
>       config={config}
>       onChange={newContent => console.log(newContent)}
>     />
>   )
> }
> ```
> 
> It seems that the config object is not allowed to be inside of the react function component (as it is in the readme.md)

Yes! I solved my problem realocating the options in a let.
