### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by sajjadghasemi** [jodit/jodit-react#281]
Many errors on updating react from 18.** -> 19.
Please update react version.

**Comment by xdan** [comment]
@Regnar110  @sajjadghasemi  Hi, did you try 5.0.0-beta.3 ?

**Comment by sajjadghasemi** [comment]
> @Regnar110 @sajjadghasemi Hi, did you try 5.0.0-beta.3 ?

Not yet, I will try as soon as possible, Thank you!

**Comment by Regnar110** [comment]
> @Regnar110 @sajjadghasemi Hi, did you try 5.0.0-beta.3 ?

Hey,  i tried yesterday. Everything seems to work after upgrading to v5

**Comment by sajjadghasemi** [comment]
> > @Regnar110 @sajjadghasemi Hi, did you try 5.0.0-beta.3 ?
> 
> Hey, i tried yesterday. Everything seems to work after upgrading to v5

I tried it also, It works but still i have a console error in both server and client side like this:
ChunkLoadError: Loading chunk 164 failed. (error: http://localhost:3000/build/164.fat.min.js)

I tried many solution in next and react to solve it but i could not yet.

BTW many thanks!

**Comment by Regnar110** [comment]
> Refere

It seems that i also have this chunk loading error. 
I used dynamic import as mentioned here https://github.com/jodit/jodit-react/issues/236 with ssr set to false.

**Comment by LaciTheTroll** [comment]
Same problem here!
