### ISSUE TITLE
this.selection undefined

### ISSUE THREAD

**Issue by josera21** [jodit/jodit-react#54]
I am using the uploader options to upload images, this is my config file: 

```
{
    readonly: false,
    language: i18n.language.substring(0,2),
    uploader: { 
      url: 'http://localhost:6002/v1/files',
      filesVariableName: () => {
        return "file"
      },
      format: "json",
      prepareData: (data) => {
        data.append('is_public', "true")
        console.log("data", data)
      },
      isSuccess: (resp) => {
        // resp is the response from the API with endpoint used on url property.
        console.log("success", resp)
        return resp
      },
      process: (resp) => {
        // process response that comes of the isSucess function
        console.log("resp", resp)
        return {
          files: resp.data.files || [],
          path: resp.data.path,
          baseurl: resp.data.baseurl,
          error: resp.data.error,
          message: resp.data.message
        };
      },
      defaultHandlerSuccess: (data) => {
        // insert image on html content
        console.log("handler success", data)
        console.log("this", editor)
        
        let i, field = 'files';                      
        if (data[field] && data[field].length) {
          for (i = 0; i < data[field].length; i += 1) {
            this.selection.insertImage(data.path);
          }
        }
      },
      error: (error) => {
        console.log("error", error)
      }
    }
  }
```

Everything works fine, but the handlerSuccess method break when `this.selection.insertImage` it throw a error `undefined has no properties` how I can access to `this` instance on react ?  

UPDATE: 

I remove the arrow functions and changed for `function` now I can access to `this` instance, but in `this.selection.insertImage()` is throw an error "o is undefined"

**Comment by josera21** [comment]
I found the solution [here](https://stackoverflow.com/questions/59781249/how-to-properly-insert-uploaded-image-with-jodit-editor#)

It seems like insertImage, need a couple of parameters  to work correctly. 

Closing issue.

**Comment by zhangyuting1** [comment]
hi @josera21 .
It will be appreciated if you could help paste a working example: 
how to upload local image to backend server, then replace the image url returned from backend, load the image and display  in the richtext area. 

Thank you!

**Comment by josera21** [comment]
@zhangyuting1 Of course, as soon as I can I will pass the code over here.

**Comment by zhangyuting1** [comment]
> @zhangyuting1 Of course, as soon as I can I will pass the code over here.

But at first, I meet the same issue: 
**"Cannot read property 'selection' of undefined"** when I try to call insertImage function. Also that solution did not work. 
this.selection.insertImage(imageurl, null, 250);

May I know how you fix it.

**Comment by zhangyuting1** [comment]
And @josera21 , may I learn how you handle upload multi images one time, for now, if we select multi images, it will send multi file with same name.  But in that case, the backend can only accept the first one I think. 
![image](https://user-images.githubusercontent.com/7311213/88024305-0f79d700-cb65-11ea-91b9-796ce4bd25ed.png)

So how you assemble the data in frontend?  Thanks a lot

**Comment by josera21** [comment]
@zhangyuting1

**Comment by josera21** [comment]
@zhangyuting1 

```
const editorConfig = {
    readonly: false,
    language: i18n.language.substring(0,2),
    uploader: { 
      url: `${FILES_URL}${FILES_API_VERSION}/files`,
      filesVariableName: () => {
        return "file"
      },
      format: "json",
      prepareData: function (data) {
        data.append('is_public', "true")
        console.log("data", data)
        uploadBegin()
      },
      isSuccess: function (resp) {
        // this event is fired when the upload from the backend execute ok.
        // resp is the response from the API with endpoint used on url property.
        console.log("success", resp)
        showNotification({
          title: t('common.saved'),
          message: resp.message,
          type: "success"
        })
        uploadFinish()
        return resp
      },
      process: function (resp) {
        // process response that comes from the API.
        // this method need to return this particular format in order that
        // jodit work properly.
        const { data, message } = resp
        console.log("resp", resp)
        const files = [
          `${data.relative_url}${data.name}`
        ]
        return {
          files: files || [],
          path: data.location,
          baseurl: data.base_url,
          error: "",
          message
        };
      },
      defaultHandlerSuccess: function (data) {
        // insert image on html content
        // data is the format that comes from the process method. 
        console.log("handler success", data)
        
        let i, field = 'files';                      
        if (data[field] && data[field].length) {
          for (i = 0; i < data[field].length; i += 1) {
            this.selection.insertImage(data.baseurl + data[field][i], null, 300);
          }
        }
      },
      error: function (error) {
        console.log("error", error)
        showNotification({
          title: t('common.error'),
          message: error.toString(),
          type: "danger"
        })
        uploadFinish()
      }
    }
  }
```

**Comment by zhangyuting1** [comment]
> showNotification

May I konw is that your defined function, and it will popup msg on the jodit richtext area?

**Comment by jesse-wang** [comment]
`this.selection.inserImage` will throw an error. The correct way for me is `this.jodit.selection.inserImage`, oh and don't use arrow function as you won't get the correct `this`.

**Comment by josera21** [comment]
> `this.selection.insertImage` will throw an error. The correct way for me is `this.jodit.selection.insertImage`, oh and don't use arrow function as you won't get the correct `this`.

Thanks, I will keep this in mind when I make a refactor.

**Comment by HaTrang1386** [comment]
I fix it by create and using the _this variable as shown below
Remember not using arrow functions
```js
defaultHandlerSuccess: function (data, resp) {
  var i,
    field = 'files';
 const _this = this.jodit ?? this
  if (data[field] && data[field].length) {
    for (i = 0; i < data[field].length; i += 1) {
      _this.s.insertImage(data.baseurl + data[field][i]);
    }
  }
},
```
