### ISSUE TITLE
Mouse double click creates empty <p></p>

### ISSUE THREAD

**Issue by ryisamu** [jodit/jodit-react#62]
Hi,

I just started adding the editor and one of the thing I noticed when I double click mouse on the editor is that it will generate empty <p></p>which I can see on either source mode or console.

Any idea why this is happening and possible to resolve?

**Comment by xdan** [comment]
You can disable this behaviour https://xdsoft.net/jodit/doc/options/addNewLineOnDBLClick/

**Comment by ryisamu** [comment]
Thanks, it works!
