### ISSUE TITLE
How to enable image upload (not as base64uri) with nodejs

### ISSUE THREAD

**Issue by Segun98** [jodit/jodit-react#64]
Please help, I've been trying to upload images with Jodit, Base64URI is simply not efficient, it bloats my database, how else can i enable Image uploads?

**Comment by pisacode** [comment]
Just add a config element 

```
const config = {
      readonly: false, // all options from https://xdsoft.net/jodit/doc/
      "uploader": {
        "insertImageAsBase64URI": true
      },
    }
```

**Comment by Segun98** [comment]
> Just add a config element
> 
> ```
> const config = {
>       readonly: false, // all options from https://xdsoft.net/jodit/doc/
>       "uploader": {
>         "insertImageAsBase64URI": true
>       },
>     }
> ```

I literally said "not as base64uri"

**Comment by xdan** [comment]
@Segun98 Did you solve the problem?

**Comment by Segun98** [comment]
Unfortunately, no.

**Comment by xdan** [comment]
```js
const config = {
      readonly: false, // all options from https://xdsoft.net/jodit/doc/
      "uploader": {
        "insertImageAsBase64URI": false // disable this behaviour
       url: 'connector/index.php?action=fileUpload'
      },
    }
```
After paste - the image will be uploaded to the server. You need to use some server-side script - for example PHP https://github.com/xdan/jodit-connectors

**Comment by Segun98** [comment]
I will try to implement it with Nodejs. Thank you.

**Comment by HaseebIqbal33** [comment]
> I will try to implement it with Nodejs. Thank you.

can you tell me how you solve the issue i am facing the same issue
