### ISSUE TITLE
Pasting simple text with Ctrl+V inserts it at the beginning instead of current cursor position

### ISSUE THREAD

**Issue by antonioh** [jodit/jodit-react#65]
This is happening in:
- Firefox 76.0.1 (64 bit)
- Windows 10

It happens also on the demo page: (https://xdsoft.net/jodit/) as shown in the attached gif where it can be seen how I:

1. Select text from the Editor
2. Position cursor on the next line
3. Press Ctrl+V and text is inserted at the very top instead of cursor position
4. Repeate copy, position cursor on nexte line and Ctrl+V -> Text is inserted again at the very top

![joditEditor-paste](https://user-images.githubusercontent.com/722865/82435873-39dfe300-9a95-11ea-9a3d-7fc826f6dfa4.gif)

**Comment by kee23** [comment]
Can you repost this to: https://github.com/xdan/jodit/issues

This seems like an issue with the core Jodit library. This project simply provides a React friendly wrapper around Jodit, so it won't be able to fix this underlying issue.

**Comment by antonioh** [comment]
ok, I'll post it there and closing the issue here. Thank you
