### ISSUE TITLE
Text aligned to center/middle by default when start typing

### ISSUE THREAD

**Issue by Mikco11** [jodit/jodit-react#66]
Hello,

i just started using jodit-react in my project and i found out this bug when i start typing into editor text is aligned to center / middle by default;

Here is how i set up editor based on example here on GitHub

`    <JoditEditor
              ref={r => (this.joditEditor = r)}
              tabIndex={1}
              value={this.props.editorHtmlValue}
              config={{
                showCharsCounter: false,
                showWordsCounter: false,
                showXPathInStatusbar: false,
                toolbar: !this.props.toolbarDisabled,
                readonly: this.props.readOnly,
                spellcheck: false,
                language: 'de',
                placeholder: this.props.placeholder,
                buttons:                  'paragraph,,,underline,italic,eraser,|,ul,ol,|,outdent,indent,|,,link,table,image,|,align,undo,redo,selectall,paste,copyformat,|,hr'
              }}
              onBlur={newContent => this.handleChange(newContent)} // preferred to use only this option to update the content for performance reasons
              onChange={newContent => {}}
            />`

`editorHtmlValue` is HTML string from Redux state variable.
`handleChange` function just set HTML string in Redux.

When i change align to left the next texts I type is OK.

**Comment by SaschaVanEssen** [comment]
I have the same issue. Did you find a solution yet?

**Comment by SaschaVanEssen** [comment]
In my case I had some global css `text-align: center;` which was applied to the editor as well. I fixed it by overriding with
`.jodit-container {
    text-align: initial;
}`

**Comment by Mikco11** [comment]
@SaschaVanEssen :slightly_smiling_face: I think i solved it similar way, but forgot to add comment with solution.
So i will close it.
