### ISSUE TITLE
onBlur is not available anymore?

### ISSUE THREAD

**Issue by w3ever** [jodit/jodit-react#91]
![image](https://user-images.githubusercontent.com/46147841/92295975-62b3b780-ef62-11ea-8671-cb8538bf45a3.png)

this is an example of a source code. 

I've added the onBlur event but I can't get the correct content.

![image](https://user-images.githubusercontent.com/46147841/92296021-ba522300-ef62-11ea-85ce-7a6f82ec2864.png)

**Comment by thewhiterabbit1994** [comment]
I have the same Issue. I used Jodit 6 months ago without any problem and it is still working in production. but when I tried to install it on my new project, I have the same issue.

the same error:  (TypeError value must be string)

and I get exactly the same as the image above.

**Comment by zoran123456** [comment]
I am using `onBlur={newContent => console.log("cnt", newContent.target.innerHTML)}`
